default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: converter_development
  username: postgres
  password: 1988iloveyou

test:
  <<: *default
  database: converter_test
  username: postgres
  password: 1988iloveyou


production:
  <<: *default
  database: d2971plb4n45lr
  host: ec2-54-228-182-57.eu-west-1.compute.amazonaws.com
  port: 5432
  username: zehmhcnoseayuq
  password: e2687081198dd6de3e76add0b056227f2357d86eee262a9432c32faad7776016
