default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: converter_development
  username: postgres
  password: 1988iloveyou

test:
  <<: *default
  database: converter_test
  username: postgres
  password: 1988iloveyou


production:
  <<: *default
  database: d7edqs5v83revc
  host: ec2-54-235-181-120.compute-1.amazonaws.com
  port: 5432
  username: pggfunnhbgcznu
  password: 621dd85ff6801175eac7ad4c0d44661a7224247d63c962c4dea2dd45b2b50324
